<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="ja">
<!--<![endif]-->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>株式会社イトモ</title>
	<meta name="description" content="弊社はWEB集客の支援とフランチャイズの加盟店を増やす支援をメインに事業展開しております。成果を出し続けることはもちろんのこと、現状に満足せず、「よりよい成功を」実現するために、必要なことを分野問わず、実施しています。">
	<meta name="author" content="Codrops" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- favicon generated by http://realfavicongenerator.net/ -->
	<meta name="format-detection" content="telephone=no">

		<!-- Site favicons -->
		<link rel="shortcut icon" href="/img/favicon/favicon24px.png">
		<link rel="apple-touch-icon" href="/img/favicon/favicon48px.png">
		<link rel="apple-touch-icon" sizes="96x96" href="/img/favicon/favicon96px.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/img/favicon/favicon144px.png">
	<!-- end favicon links -->
	<link rel="stylesheet" href="/css/bootstrap.min.css" />
	<link rel="stylesheet" href="/css/normalize.min.css">
	<link rel="stylesheet" href="/css/animate.min.css">
	<link rel="stylesheet" href="/css/flickity.min.css">
	<link rel="stylesheet" href="/css/styles.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
	<?php get_header(); ?>
</head>

<body>
	<!--[if lt IE 8]>
	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<div class="container-fluid">
		<div class="row">
			<div class="header-nav-wrapper">
				<div class="logo">
					<a href="/"><img src="/img/logo.png" alt="株式会社イトモ"></a>
				</div>
				<div class="primary-nav-wrapper">
					<nav>
						<ul class="primary-nav">
							<li><a href="#business-info">事業内容</a></li>
							<li><a href="#company-info">会社概要</a></li>
							<li><a href="#form-contact">お問い合わせ</a></li>
						</ul>
					</nav>
<!-- 					<div class="secondary-nav-wrapper">
						<ul class="secondary-nav">
							<li class="subscribe"><a href="#get-started">Subscribe</a></li>
							<li class="search"><a href="#search" class="show-search"><i class="fa fa-search"></i></a></li>
						</ul>
					</div> -->
					<div class="search-wrapper">
						<ul class="search">
							<li>
								<input type="text" id="search-input" placeholder="Start typing then hit enter to search">
							</li>
							<li>
								<a href="#" class="hide-search"><i class="fa fa-close"></i></a>
							</li>
						</ul>
					</div>
				</div>
				<div class="navicon">
					<a class="nav-toggle" href="#"><span></span></a>
				</div>
			</div>
		</div>
	</div>
	<header class="hero">
		<div class="carousel">

			<div class="carousel-cell" style="background-image: url(/img/hero-bg-01.jpg);">
				<div class="hero-bg">
					<div class="container">
						<div class="row">
							<div class="col-md-12 text-center">
								<h1 class="wp1">Success Good More For You<br>〜よりよい成功をあなたに〜</h1>
							</div>
						</div>
						<div class="row">
							<div class="col-md-8 col-md-offset-2 hero-intro-text wp3">
								<p>Morning spider will bring good luck and customers
We also want to be…</p>
							</div>
						</div>
					</div>
				</div>
			</div>
<!-- 			<div class="carousel-cell" style="background-image: url(/img/hero-bg-03.jpg);">
				<div class="hero-bg">
					<div class="container">
						<div class="row">
							<div class="col-md-12 text-center">
								<h1 class="wp1">テキストが入ります。テキストが入ります。テキストが入ります。</h1>
							</div>
						</div>
						<div class="row">
							<div class="col-md-8 col-md-offset-2 hero-intro-text wp3">
								<p>テキストが入ります。テキストが入ります。テキストが入ります。</p>
							</div>
						</div>
					</div>
				</div>
			</div> -->
		</div>
		<div class='mouse-container'>
			<a href="#intro">
				<div class='mouse'>
					<span class='scroll-down'></span>
				</div>
			</a>
		</div>
	</header>

	<!-- SECTION: Articles -->
	<section class="latest-articles has-padding alternate-bg" id="business-info">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-4">
					<h4>事業内容</h4>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<article class="article-post">

							<div class="article-image has-overlay" style="background-image: url(img/article-01.jpg)">
							</div>
							<figure>
								<figcaption>
									<h2>インターネット広告業</h2>
									<p>PPC（Yahoo／Google）広告／SNS（Facebook・LINEなど）広告／サイト制作（ランディングページ含む）／web分析・解析　など</p>
								</figcaption>
							</figure>

					</article>
				</div>
				<div class="col-md-4">
					<article class="article-post">

							<div class="article-image has-overlay" style="background-image: url(img/article-02.jpg)">
							</div>
							<figure>
								<figcaption>
									<h2>コンテンツ制作業</h2>
									<p>HP、LPの制作、バナー作成、記事コンテンツ作成　など</p>
								</figcaption>
							</figure>
						</a>

					</article>
				</div>
				<div class="col-md-4">
					<article class="article-post">

							<div class="article-image has-overlay" style="background-image: url(img/article-03.jpg)">
							</div>
							<figure>
								<figcaption>
									<h2>フランチャイズコンサルティング業</h2>
									<p>加盟の戦略立案、営業資料作成やメールマガジンやスクリプト作成、各契約書の作成　など</p>
								</figcaption>
							</figure>
						</a>

					</article>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<article class="article-post">

							<div class="article-image has-overlay" style="background-image: url(img/article-05.jpg)">
							</div>
							<figure>
								<figcaption>
									<h2>営業代行業、マッチング事業</h2>
									<p>アポイント獲得／セミナー集客／パートナー企業様（資金調達やアプリやツールなど）のご紹介　など</p>
								</figcaption>
							</figure>

					</article>
				</div>
				<div class="col-md-4">
					<article class="article-post">

							<div class="article-image has-overlay" style="background-image: url(img/article-04.jpg)">
							</div>
							<figure>
								<figcaption>
									<h2>ウェブメディア運営業</h2>

								</figcaption>
							</figure>
						</a>

					</article>
				</div>
				<div class="col-md-4">
					<article class="article-post">

							<div class="article-image has-overlay" style="background-image: url(img/article-06.jpg)">
							</div>
							<figure>
								<figcaption>
									<h2>各種コスト削減業務</h2>
									<p>電気代の削減／賃貸費用の削減　など</p>
								</figcaption>
							</figure>
						</a>

					</article>
				</div>
			</div>

		</div>
	</section>
	<!-- END SECTION: Articles -->

	<!-- SECTION: Intro -->
	<section class="collective has-padding" id="intro">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h4>ご挨拶</h4>
				</div>
				<div class="col-md-9">
					<p>弊社はWEB集客の支援とフランチャイズの加盟店を増やす支援をメインに事業展開しております。</p>
					<p>成果を出し続けることはもちろんのこと、現状に満足せず、「よりよい成功を」実現するために、必要なことを分野問わず、実施しています。</p>
					<p>そのためには、最先端の集客手法や情報を知り、パートナー企業様とどのようなプロジェクトを組んでいくかを常に考え、お客様に還元していきます。</p>
					<p>関わっていただいたお客様やパートナー企業様の可能性を最大限に引き出し、「私たち」とだから最大限以上のパフォーマンスが発揮できていると言っていただけるように、日々邁進して参ります。</p>
				</div>
			</div>
		</div>
	</section>
	<!-- END SECTION: Intro -->
	<!-- SECTION: Crew -->
	<section class="crew has-padding alternate-bg" id="company-info">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h4>会社概要</h4>
				</div>


				<div class="col-md-9">
<table class="table">
<tbody><tr>
<th>会社名</th>
<td>株式会社イトモ</td>
</tr>
<tr>
<th>役員</th>
<td>代表取締役　伊藤　正浩</td>
</tr>

<tr>
<th>設立年月日</th>
<td>2017年4月</td>
</tr>
<tr>
<th>連絡先</th>
<td>
	TEL ○○○-○○○-○○○ ／ FAX ○○○-○○○-○○○
</td>
</tr>
<tr>
<th>URL</th>
<td>
	itomo.co.jp
</td>
</tr>
<tr>
<th>事業内容</th>
<td>
	インターネット広告業<br>
	WEB制作事業<br>
	WEBマーケティング戦略の立案・設計
</td>
</tr>
<tr>
<th>アクセス</th>
<td>
〒142-0062<br>
東京都品川区小山4-4-16　ケントハウス202</td>
</tr>
<tr>
<td colspan="2" style="padding-top: 20px;" id="gmap">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d405.421443678626!2d139.70312212880773!3d35.618565854329375!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188ada314d2955%3A0x240e608bbf1f5757!2z44CSMTQyLTAwNjIg5p2x5Lqs6YO95ZOB5bed5Yy65bCP5bGx77yU5LiB55uu77yUIOOCseODs-ODiOODj-OCpuOCuQ!5e0!3m2!1sja!2sjp!4v1491466781749" width="600" height="450" frameborder="0" style="width:100%;border:0;pointer-events: none;" allowfullscreen></iframe></td>
</tr>
</tbody></table>
				</div>

			</div>
		</div>
	</section>
	<!-- END SECTION: Crew -->

	<!-- SECTION: Freebies -->
	<!-- <section class="freebies has-padding" id="freebies">

		<div class="container freebies-intro">
			<div class="row">
				<div class="col-md-12">
					<h4>Freshest Freebies</h4>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 content-left">
					<p>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。</p>
				</div>
				<div class="col-md-6 content-right">
					<p>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。</p>
				</div>
			</div>
		</div>

	</section> -->
	<!-- END SECTION: Freebies -->

	<!-- SECTION: Get started -->
	<!-- <section class="get-started has-padding text-center" id="get-started">
		<div class="container">
			<div class="row">
				<div class="col-md-12 wp4">
					<h2>テキストテキストテキストテキスト</h2>
				</div>
			</div>
		</div>
	</section> -->
	<!-- END SECTION: Get started -->


	<!-- SECTION: Get started -->
	<section class="form-contact has-padding" id="form-contact">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<h4>お問い合わせ</h4>
				</div>
				<div class="col-md-7">

					<?php echo do_shortcode('[contact-form-7 id="5" title="お問い合わせ"]'); ?>

				</div>
			</div>
		</div>
	</section>
	<!-- END SECTION: Get started -->

<?php get_footer(); ?>

	<!-- SECTION: Footer -->
	<footer class="footer-bg">
		<div class="container">
<!-- 			<div class="row">
				<div class="col-md-4 footer-branding">
					<img class="footer-branding-logo" src="/img/logo-footer.png" alt="株式会社イトモ">
					<p>A free website template created exclusively for <a href="https://tympanus.net/codrops/"><em>Codrops</em></a></p>
				</div>
			</div> -->
			<div class="row">
				<div class="col-md-7 footer-nav">
					<ul class="footer-primary-nav">
						<li><a href="#business-info">事業内容</a></li>
						<li><a href="#company-info">会社概要</a></li>
						<li><a href="#form-contact">お問い合わせ</a></li>
						<li><a href="privacy.html">プライバシーポリシー</a></li>
					</ul>

<!-- 					<ul class="footer-secondary-nav">
						<li><p>Copyright © cessgumo All Rights Reserved.</p></li>
					</ul> -->
				</div>
				<div class="col-md-5 footer-branding footer-nav">
					<img class="footer-branding-logo" src="/img/logo-footer.png" alt="株式会社イトモ">
					<p>
					株式会社イトモ<br>
					〒142-0062 東京都品川区小山4-4-16　ケントハウス202<br>
					TEL 03-4405-5453</p>
				</div>
			</div>
			<p class="copy text-center">Copyright © cessgumo All Rights Reserved.</p>
		</div>
	</footer>
	<!-- END SECTION: Footer -->

	<!-- JS CDNs -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
	<script src="https://vjs.zencdn.net/5.4.6/video.min.js"></script>
	<!-- jQuery local fallback -->
	<script>
	window.jQuery || document.write('<script src="/js/min/jquery-1.11.2.min.js"><\/script>')
	</script>
	<!-- JS Locals -->
	<script src="/js/min/bootstrap.min.js"></script>
	<script src="/js/min/modernizr-2.8.3-respond-1.4.2.min.js"></script>
	<script src="/js/min/jquery.waypoints.min.js"></script>
	<script src="/js/min/flickity.pkgd.min.js"></script>
	<script src="/js/scripts.js"></script>
	<script>
$(function() {
        var map = $('iframe');
        map.css('pointer-events', 'none');
        $('#gmap').click(function() {
            map.css('pointer-events', 'auto');
        });
        map.mouseout(function() {
            map.css('pointer-events', 'none');
        })
    })
</script>
	<!-- Google Analytics: change UA-XXXXX-X to be your site's ID and uncomment -->
	<!--
	<script>
	(function(b, o, i, l, e, r) {
		b.GoogleAnalyticsObject = l;
		b[l] || (b[l] =
			function() {
				(b[l].q = b[l].q || []).push(arguments)
			});
		b[l].l = +new Date;
		e = o.createElement(i);
		r = o.getElementsByTagName(i)[0];
		e.src = '//www.google-analytics.com/analytics.js';
		r.parentNode.insertBefore(e, r)
	}(window, document, 'script', 'ga'));
	ga('create', 'UA-XXXXX-X', 'auto');
	ga('send', 'pageview');
	</script>
	-->
</body>

</html>